config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :postings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :postings
end

app/models/posting.rb
class Posting < ApplicationRecord
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def show
    @company = Company.find(params[:id])
  end
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  def index
    @postings = Posting.all
  end

  def show
    @posting = Posting.find(params[:id])
  end

  def new
    @posting=Posting.new
    @companies = Company.all
  end

  def create
    Posting.create(posting_params)
    redirect_to postings_path
  end

  def edit
    @posting=Posting.find(params[:id])
    @companies = Company.all

  end

  def update
    @posting = Posting.find(params[:id])
    @posting.update(posting_params)
    redirect_to postings_path
  end

  private

  def posting_params
    params.require(:posting).permit(:position, :location, :job_description, :company_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/views/companies/show.erb
<body class="company_show">
  <div>
    <div class='posting_show_heading'>
      <h3><%= @company.name %></h3>
      <p><%= @company.address %></p>
      <img class="posting_show_logo" src="<%= @company.logo %>" alt="">
    </div>

    <div>
      <img class="posting_show_map" src="<%= asset_path('qcenter.png') %>" alt="Map to Q center"><img class="posting_show_image" src="<%= @company.main_image %>" alt="">
    </div>

    <div class='company_details'>
      <div>
        <h5>EMPLOYER PROFILE</h5>
        <p><%= @company.profile %></p>
      </div>
      <div>
        <h5>ABOUT THIS EMPLOYER</h5>
        <p><%= @company.name %></p>
        <p><%= @company.address%></p>
      </div>
      <div>
        <h5>MANAGED BY</h5>
        <p>Enter management information here</p>
      </div>
    </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/postings/_form.erb
<%= form_for @posting do |f|%>
  <div>
    <%= f.label :position %>
    <%= f.text_area :position %>
  </div>
  <div>
    <%= f.label :location %>
    <%= f.text_area :location %>
  </div>
  <div>
    <%= f.label :job_description %>
    <%= f.text_area :job_description %>
  </div>
  <div>
    <%= f.label :company_id %>
    <%= f.select :company_id, options_from_collection_for_select(@companies, :id, :name) %>
  </div>

  <%= f.submit "Submit" %>
<% end %>

app/views/postings/edit.erb
<div class='new_posting_form'>
  <%= render :partial => "form" %>
</div>

app/views/postings/index.erb
<body class="postings_index">
  <div>
    <%= link_to "Post new Job", new_posting_path %>
  </div>
  <div class="all_postings_section">
    <% @postings.each do |posting| %>
      <div class='posting_card'>
        <img class="posting_image" src="<%= posting.company.main_image %>" alt="<%= posting.position %>">
        <div class="posting_info">
          <img class="posting_logo" src="<%= posting.company.logo %>" alt="<%= posting.company.name %>">
          <p> <%= link_to posting.position, posting_path(posting.id)%></p>
          <p> <%= link_to posting.company.name, company_path(posting.company.id) %></p>
          <p> <%= posting.location %></p>
        </div>
      </div>
    <% end %>
  </div>
</body>

app/views/postings/new.erb
<div>
  <div class='new_posting_form'>
    <%= render :partial => "form" %>
  </div>
  <div>
    <%= link_to "Back to all Postings", postings_path %>
  </div>
</div>

app/views/postings/show.erb
<body class="postings_show">
  <div>
    <div class='posting_show_heading'>
      <h3><%= @posting.position %></h3>
      <img class="posting_show_logo" src="<%= @posting.company.logo %>" alt="">
    </div>
    <div>
      <img class="posting_show_map" src="<%= asset_path('qcenter.png') %>" alt="Map to Q center"><img class="posting_show_image" src="<%= @posting.company.main_image %>" alt="">
    </div>
    <div>
      <h5>About this job</h5>
      <p><%= @posting.job_description %></p>
    </div>
  </div>
  <div>
    <%= link_to "Edit this posting", edit_posting_path(@posting.id) %>
  </div>
</body>